apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeploy.fullname" . }}-secret
  labels:
    {{- include "kubeploy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.sessionSecret }}
  session-secret: {{ .Values.config.sessionSecret | b64enc | quote }}
  {{- else }}
  session-secret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.registry.username }}
  registry-username: {{ .Values.registry.username | b64enc | quote }}
  {{- else }}
  registry-username: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.registry.password }}
  registry-password: {{ .Values.registry.password | b64enc | quote }}
  {{- else }}
  registry-password: {{ "" | b64enc | quote }}
  {{- end }}
---
{{- if and .Values.registry.url .Values.registry.username .Values.registry.password }}
apiVersion: v1
kind: Secret
metadata:
  name: kubeploy-registry-creds
  labels:
    {{- include "kubeploy.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.registry.url .Values.registry.username .Values.registry.password (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc | quote }}
{{- end }}
