replicaCount: 1

image:
  repository: ghcr.io/kubeploy/kubeploy
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: kubeploy.example.com
  tls: false
  tlsSecretName: ""

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce

serviceAccount:
  create: true
  name: kubeploy
  annotations: {}

rbac:
  create: true

registry:
  url: ""
  username: ""
  password: ""

config:
  defaultNamespace: kubeploy-apps
  defaultDomain: ""
  sessionSecret: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

buildkit:
  image:
    repository: moby/buildkit
    tag: v0.21.1
  persistence:
    size: 10Gi
    storageClass: ""
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: "2"

nodeSelector: {}
tolerations: []
affinity: {}
